services:
  backend:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: lanchedasi-api
    restart: always
    environment:
      - PORT=8000
    networks:
      - lanchedasi-network

  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: lanchedasi-web
    restart: always
    depends_on:
      - backend
    networks:
      - lanchedasi-network

  nginx-lanche:
    image: nginx:alpine
    container_name: lanchedasi-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - lanchedasi-network

networks:
  lanchedasi-network:
    driver: bridge
